baseURL = "https://ghamza-blog.github.io"
languageCode = "en-us"
title = "Blog.Ghamza"
theme = "ghamza-archie"
copyright = "Â© Hamza Jadid"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 10

[params]
mode = "auto"
useCDN = true
subtitle = "Personal blog to share computer science and software engineering articles."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Ghamza-Jd"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/ghamza.tech"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hamza-jadid/"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://www.linkedin.com/in/hamza-jadid/"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2
