baseURL = "https://blog.ghamza.dev"
language = "en-us"
title = "Ghamza Blog"
theme = "baseet"
copyright = "Â© Hamza Jadid"
paginate = 10

[params]
mode = "dark"
useCDN = true
subtitle = "Personal blog to share computer science and software engineering articles."
support_text = "ğŸ•Šï¸ğŸ‡µğŸ‡¸ I stand with humanity, I stand with Palestine ğŸ‡µğŸ‡¸ğŸ•Šï¸"
gtag_key = "G-M9GYS9Z1XC"

[params.giscus]
enabled = true
repo = "ghamza-blog/ghamza-blog.github.io"
repo_id = "R_kgDOHMIi9w"
category_id = "DIC_kwDOHMIi984COoB4"
mapping = "url"
reactions_enabled = 1
emit_metadata = 1
input_position = "top"
theme = "preferred_color_scheme"
loading = "lazy"
lang = "en"
crossorigin = "anonymous"

[params.favicon]
apple_touch_icon = "https://static.ghamza.dev/icons/apple-touch-icon.png"
s32 = "https://static.ghamza.dev/icons/favicon-32x32.png"
s16 = "https://static.ghamza.dev/icons/favicon-16x16.png"
manifest = "https://static.ghamza.dev/icons/site.webmanifest"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Ghamza-Jd"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/ghamza.tech"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hamza-jadid"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://blog.ghamza.dev/index.xml"

[[menu.main]]
name = "Archives"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
noHl = false
style = "witchhazel"
tabWidth = 4
