baseURL = "https://blog.ghamza.dev"
languageCode = "en-us"
title = "Ghamza Blog"
theme = "ghamza-archie"
copyright = "Â© Hamza Jadid"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 10

[params]
mode = "auto"
useCDN = true
subtitle = "Personal blog to share computer science and software engineering articles."
gtag_key = "G-M9GYS9Z1XC"
support_text = "ğŸ•Šï¸ğŸ‡µğŸ‡¸ I stand with humanity, I stand with Palestine ğŸ‡µğŸ‡¸ğŸ•Šï¸"
giscus_enabled = true
giscus_data_repo = "ghamza-blog/ghamza-blog.github.io"
giscus_data_repo_id = "R_kgDOHMIi9w"
giscus_data_category_id = "DIC_kwDOHMIi984COoB4"
giscus_data_mapping = "url"
giscus_data_reactions_enabled = "1"
giscus_data_emit_metadata = "1"
giscus_data_input_position = "top"
giscus_data_theme = "preferred_color_scheme"
giscus_data_lang = "en"
giscus_data_loading = "lazy"
giscus_crossorigin = "anonymous"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Ghamza-Jd"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/ghamza.tech"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hamza-jadid/"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://blog.ghamza.dev/index.xml"

[[menu.main]]
name = "Archives"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2
