baseURL = "https://blog.ghamza.dev"
languageCode = "en-us"
title = "Ghamza Blog"
theme = "ghamza-archie"
copyright = "Â© Hamza Jadid"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 10

[params]
mode = "auto"
useCDN = true
subtitle = "Personal blog to share computer science and software engineering articles."
gtag_key = "G-M9GYS9Z1XC"
support_text = "ğŸ•Šï¸ğŸ‡µğŸ‡¸ I stand with humanity, I stand with Palestine ğŸ‡µğŸ‡¸ğŸ•Šï¸"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Ghamza-Jd"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/ghamza.tech"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hamza-jadid/"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://blog.ghamza.dev/index.xml"

[[menu.main]]
name = "Archives"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2
